using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

namespace RxSourceGenerator;

[Generator]
public class RxIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Безусловно генерируем базовый класс при каждой инициализации
        context.RegisterPostInitializationOutput(ctx =>
        {
            var emptyClass = @"// <auto-generated/>
namespace RxMethodGenerator
{
    public static partial class RxGeneratedMethods { }
}";
            ctx.AddSource("RxGeneratedMethods.g.cs", emptyClass);
        });

        // Найти все обращения вида example.Rx...
        var memberAccessNodes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is MemberAccessExpressionSyntax { Name.Identifier.ValueText: var name } && name.StartsWith("Rx"),
                transform: static (ctx, _) => ctx.Node as MemberAccessExpressionSyntax)
            .Where(static ma => ma is not null)!;

        var compilationAndCandidates = context.CompilationProvider.Combine(memberAccessNodes.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, GenerateForAllEventsOfUsedTypes);
    }

    private static string EncodeClassName(string fullName)
    {
        // Заменяем символы, которые не разрешены в имени файла
        var sb = new StringBuilder();
        foreach (var c in fullName)
        {
            if (char.IsLetterOrDigit(c)) sb.Append(c);
            else sb.Append('_');
        }
        return sb.ToString();
    }

    private static void GenerateForAllEventsOfUsedTypes(SourceProductionContext context, (Compilation compilation, ImmutableArray<MemberAccessExpressionSyntax> candidates) source)
    {
        var (compilation, candidates) = source;
        if (candidates.IsDefaultOrEmpty) return;

        var typeSet = new HashSet<string>();
        var typeSymbols = new List<INamedTypeSymbol>();

        foreach (var syntax in candidates)
        {
            var model = compilation.GetSemanticModel(syntax.SyntaxTree);
            var typeInfo = model.GetTypeInfo(syntax.Expression);
            if (typeInfo.Type is INamedTypeSymbol typeSymbol)
            {
                var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (typeSet.Add(typeName))
                    typeSymbols.Add(typeSymbol);
            }
        }

        var hashSet = new HashSet<(string ClassType, string EventName)>();

        foreach (var typeSymbol in typeSymbols)
        {
            var methodsToGenerate = new List<(string ClassType, string EventName, string EventType, List<string> ArgumentTypes, INamedTypeSymbol DelegateSymbol)>();
            
            for (INamedTypeSymbol? currentType = typeSymbol; currentType != null; currentType = currentType.BaseType)
            {
                foreach (var ev in currentType.GetMembers().OfType<IEventSymbol>())
                {
                    if (ev.Type is not INamedTypeSymbol delegateSymbol || delegateSymbol.DelegateInvokeMethod == null) continue;
                    var classTypeString = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (!hashSet.Add((classTypeString, ev.Name))) continue;

                    string eventTypeString = delegateSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    List<string> typeArguments = delegateSymbol.DelegateInvokeMethod.Parameters
                        .Select(p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToList();

                    methodsToGenerate.Add((classTypeString, ev.Name, eventTypeString, typeArguments, delegateSymbol));
                }
            }
            if (methodsToGenerate.Count == 0) continue;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Reactive;");
            sb.AppendLine("using System.Reactive.Linq;");
            sb.AppendLine();
            sb.AppendLine("namespace RxMethodGenerator");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class RxGeneratedMethods");
            sb.AppendLine("    {");

            foreach (var (classType, eventName, eventType, argumentTypes, delegateSymbol) in methodsToGenerate)
            {
                string tupleTypeStr;
                string conversionStr;
                var invokeMethodParams = delegateSymbol.DelegateInvokeMethod.Parameters;

                // Генерация имён для элементов кортежа
                string GetTupleElementName(int index, IParameterSymbol param)
                {
                    var typeName = param.Type.Name;
                    return $"Item{index + 1}{typeName}";
                }

                switch (invokeMethodParams.Length)
                {
                    case 0:
                        tupleTypeStr = "System.Reactive.Unit";
                        conversionStr = "conversion => () => conversion(Unit.Default)";
                        break;
                    case 1:
                        tupleTypeStr = $"{invokeMethodParams[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {GetTupleElementName(0, invokeMethodParams[0])}";
                        conversionStr = $"conversion => arg => conversion(arg)";
                        break;
                    case 2:
                        if (invokeMethodParams[0].Type.SpecialType == SpecialType.System_Object &&
                            (delegateSymbol.ConstructedFrom.ToDisplayString().StartsWith("System.EventHandler") || eventType == "System.EventHandler"))
                        {
                            tupleTypeStr =
                                $"(object Item1Object, {invokeMethodParams[1].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {GetTupleElementName(1, invokeMethodParams[1])})";
                            conversionStr = "conversion => (sender, args) => conversion((sender, args))";
                        }
                        else
                        {
                            var tupleElements = invokeMethodParams
                                .Select((p, i) => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {GetTupleElementName(i, p)}");
                            tupleTypeStr = $"({string.Join(", ", tupleElements)})";
                            string argsTuple = string.Join(", ", invokeMethodParams.Select((p, i) => $"arg{i}"));
                            conversionStr = $"conversion => ({argsTuple}) => conversion(({argsTuple}))";
                        }
                        break;
                    default:
                        var tupleElementsDefault = invokeMethodParams
                            .Select((p, i) => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {GetTupleElementName(i, p)}");
                        tupleTypeStr = $"({string.Join(", ", tupleElementsDefault)})";
                        string argsTupleDefault = string.Join(", ", invokeMethodParams.Select((p, i) => $"arg{i}"));
                        conversionStr = $"conversion => ({argsTupleDefault}) => conversion(({argsTupleDefault}))";
                        break;
                }

                sb.AppendLine($"        public static IObservable<{tupleTypeStr}> Rx{eventName}(this {classType} obj)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (obj == null) throw new ArgumentNullException(nameof(obj));");
                sb.AppendLine($"            return Observable.FromEvent<{eventType}, {tupleTypeStr}>(");
                sb.AppendLine($"                {conversionStr},");
                sb.AppendLine($"                h => obj.{eventName} += h,");
                sb.AppendLine($"                h => obj.{eventName} -= h);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var safeClassName = EncodeClassName(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            context.AddSource($"RxExtensionsFor{safeClassName}.g.cs", sb.ToString());
        }
    }
}